const parcels=[
 {survey:'124/2A',ulpin:'TN-1234-5678-9012',area:'2.50 Acres',landUse:'Residential',district:'Nagapattinam',holder:'Demo Land Holder',lat:10.7670,lng:79.8440,ror:'Patta active · Area 2.50 acres',reg:'Deed #REG-2026-0142 · Linked',tax:'Property tax paid · FY 2026',zone:'Residential Zone R2'},
 {survey:'125/1B',ulpin:'TN-1234-5678-9013',area:'1.80 Acres',landUse:'Agricultural',district:'Nagapattinam',holder:'Demo Agricultural Holder',lat:10.7690,lng:79.8470,ror:'Patta active · Area 1.80 acres',reg:'No conflicting registration found',tax:'Tax status · Current',zone:'Agricultural Zone'},
 {survey:'126/3',ulpin:'TN-1234-5678-9014',area:'3.10 Acres',landUse:'Residential',district:'Nagapattinam',holder:'Demo Property Holder',lat:10.7650,lng:79.8490,ror:'Patta active · Area 3.10 acres',reg:'Deed #REG-2026-0188 · Linked',tax:'Property tax paid · FY 2026',zone:'Residential Zone R2'}
];
const map=L.map('map',{zoomControl:false}).setView([10.7675,79.846],14);
L.control.zoom({position:'bottomright'}).addTo(map);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; OpenStreetMap contributors'}).addTo(map);
const layers={parcel:L.layerGroup().addTo(map),admin:L.layerGroup().addTo(map),zoning:L.layerGroup(),restriction:L.layerGroup()};
const shapes=[];
parcels.forEach((p,i)=>{const d=.0015;const poly=L.polygon([[p.lat-d,p.lng-d],[p.lat+d*.55,p.lng-d*1.15],[p.lat+d,p.lng+d*.35],[p.lat+d*.25,p.lng+d*1.2],[p.lat-d*1.05,p.lng+d*.75]],{color:'#1998e5',weight:2,fillColor:'#55b9ed',fillOpacity:.18});poly.bindTooltip(p.survey);poly.on('click',()=>selectParcel(i));poly.addTo(layers.parcel);shapes.push(poly)});
L.rectangle([[10.763,79.839],[10.772,79.853]],{color:'#778da1',weight:1,dashArray:'6 6',fill:false}).addTo(layers.admin);
L.rectangle([[10.764,79.843],[10.770,79.850]],{color:'#e5a42e',weight:2,fillColor:'#f6c55b',fillOpacity:.08}).addTo(layers.zoning);
let selected=0; let activeTab='ror';
function selectParcel(i){selected=i;const p=parcels[i];shapes.forEach((s,j)=>s.setStyle({weight:j===i?4:2,fillOpacity:j===i?.4:.18}));document.getElementById('ulpin').textContent=p.ulpin;document.getElementById('survey').textContent=p.survey;document.getElementById('area').textContent=p.area;document.getElementById('landUse').textContent=p.landUse;document.getElementById('district').textContent=p.district;document.getElementById('holder').textContent=p.holder;document.getElementById('selectedPill').textContent='Survey '+p.survey;renderRecord();map.setView([p.lat,p.lng],15);}
function renderRecord(){const p=parcels[selected];const data={ror:['Record of Rights',p.ror],reg:['Registration',p.reg],tax:['Property Tax',p.tax],zone:['Zoning / Master Plan',p.zone]}[activeTab];document.getElementById('recordContent').innerHTML=`<div class="record-body"><p><strong>${data[0]}</strong></p><p>${data[1]}</p><p><strong>Source:</strong> State Adapter demo · <strong>Status:</strong> linked</p></div>`}
const input=document.getElementById('parcelSearch'),suggestions=document.getElementById('suggestions');
function showSuggestions(){const q=input.value.toLowerCase();suggestions.innerHTML=parcels.filter(p=>p.survey.toLowerCase().includes(q)).map(p=>`<div data-s="${p.survey}">⌖ ${p.survey} · ${p.area}</div>`).join('');suggestions.querySelectorAll('div').forEach(el=>el.onclick=()=>{input.value=el.dataset.s;selectParcel(parcels.findIndex(p=>p.survey===el.dataset.s));suggestions.innerHTML=''})}
input.addEventListener('input',showSuggestions);document.getElementById('searchBtn').onclick=()=>{const i=parcels.findIndex(p=>p.survey.toLowerCase()===input.value.trim().toLowerCase());if(i>=0)selectParcel(i);else{suggestions.innerHTML='<div>No demo parcel found</div>'}};
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeTab=b.dataset.tab;renderRecord()});
document.querySelectorAll('.check input').forEach(c=>c.onchange=()=>{const key=c.dataset.layer;if(c.checked)layers[key].addTo(map);else map.removeLayer(layers[key])});
document.getElementById('stateSelect').onchange=e=>{if(e.target.value==='BR'){input.placeholder='Khesra No. e.g. 124/2A';toast('Bihar State Adapter selected — terminology mapped to common schema')}else toast('Tamil Nadu State Adapter selected')};
const modal=document.getElementById('modal');document.getElementById('aiCheck').onclick=()=>modal.classList.add('show');document.getElementById('closeModal').onclick=()=>modal.classList.remove('show');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('show')};document.getElementById('verifyBtn').onclick=()=>{modal.classList.remove('show');toast('Case sent to Officer Review queue')};document.getElementById('loginBtn').onclick=()=>toast('Demo login: Citizen / Officer / Admin roles are simulated');
function toast(msg){const t=document.createElement('div');t.textContent=msg;t.style='position:fixed;right:20px;bottom:20px;background:#071827;color:white;padding:13px 17px;border:1px solid #29445f;border-radius:10px;z-index:4000;font-size:12px;box-shadow:0 12px 30px #0003';document.body.appendChild(t);setTimeout(()=>t.remove(),2800)}
selectParcel(0);